#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/garbage.h"
#include "images/TitleScreen.h"
#include "images/EnterToStart.h"
#include "images/LoseScreen.h"
#include "images/Rules.h"
#include "images/WinScreen.h"
#include "images/Star.h"
#include "images/TitleScreenZero.h"
#include "images/TitleScreenOne.h"
#include "images/TitleScreenTwo.h"
#include "images/TitleScreenThree.h"
#include "images/TitleScreenFour.h"
#include "images/TitleScreenFive.h"
#include "images/TitleScreenSix.h"
#include "images/TitleScreenSeven.h"
#include "images/TitleScreenEight.h"
#include "images/TitleScreenNine.h"
#include "images/TitleScreenTen.h"
#include "images/Timer.h"
#include "images/TimeLeft.h"
#include "images/Options.h"
#include "images/Score.h"
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

#define MODE3 3

// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  RULES,
  OPTIONS,
  PLAY,
  STARTPLAYING,
  DRAWSTARS,
  WIN,
  LOSE,
};

int main(void) {
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  drawFullScreenImageDMA(TitleScreen);

  struct Sprite s1;
  s1.row = 120;
  s1.col = 120;
  s1.score = 0;
  s1.color = MAGENTA;
  struct Sprite s2;
  s2.row = 10;
  s2.col = 120;
  s2.score = 0;
  s2.color = MAGENTA;
  struct Star star1;
  star1.row = 20;
  star1.col = 20;
  star1.caught = 0;
  struct Star star2;
  star2.row = 40;
  star2.col = 60;
  star2.caught = 0;
  struct Star star3;
  star3.row = 70;
  star3.col = 40;
  star3.caught = 0;
  struct Star star4;
  star4.row = 90;
  star4.col = 70;
  star4.caught = 0;
  struct Star star5;
  star5.row = 110;
  star5.col = 20;
  star5.caught = 0;
  struct Star star6;
  star6.row = 130;
  star6.col = 60;
  star6.caught = 0;
  struct Star star7;
  star7.row = 160;
  star7.col = 40;
  star7.caught = 0;
  struct Star star8;
  star8.row = 180;
  star8.col = 70;
  star8.caught = 0;
  struct Star star9;
  star9.row = 200;
  star9.col = 20;
  star9.caught = 0;
  struct Star star10;
  star10.row = 220;
  star10.col = 60;
  star10.caught = 0;
  struct GoalTile g1;
  g1.row = 200;
  g1.rowEnd = 235;
  g1.col = 140;
  g1.colEnd = 155;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();

    switch (state) {
      case START:
        for (int i = 0; i < 912; i++) {
          if (i%20 == 0) {
            drawSprite(s2.row + (i), s2.col, s2.color);
          }
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            state = RULES;
            break;
          }
          if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            main();
          }
        }
        for (int i = 0; i < 912; i++) {
          if (i%20 == 0) {
            drawSprite(s2.row - (i), s2.col, s2.color);
          }
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            state = RULES;
            break;
          }
          if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            main();
          }
        }
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = RULES;
          break;
        }
        if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          main();
        }
        break;
      case RULES:
        drawFullScreenImageDMA(Rules);
        if (KEY_DOWN_NOW(BUTTON_START) & KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          state = OPTIONS;
        }
        if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          main();
        }
        break;
      case OPTIONS:
        drawFullScreenImageDMA(Options);
        if (KEY_DOWN_NOW(BUTTON_UP) & KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons)) {
          s1.color = MAGENTA;
          state = PLAY;
          fillScreenDMA(BLACK);
          drawImageDMA(140, 0, 56, 16, Score);
          drawChar(145, 38, '0', WHITE);
        }
        if (KEY_DOWN_NOW(BUTTON_RIGHT) & KEY_JUST_PRESSED(BUTTON_RIGHT, currentButtons, previousButtons)) {
          s1.color = CYAN;
          state = PLAY;
          fillScreenDMA(BLACK);
          drawImageDMA(140, 0, 56, 16, Score);
          drawChar(145, 38, '0', WHITE);
        }
        if (KEY_DOWN_NOW(BUTTON_DOWN) & KEY_JUST_PRESSED(BUTTON_DOWN, currentButtons, previousButtons)) {
          s1.color = WHITE;
          state = PLAY;
          fillScreenDMA(BLACK);
          drawImageDMA(140, 0, 56, 16, Score);
          drawChar(145, 38, '0', WHITE);
        }
        if (KEY_DOWN_NOW(BUTTON_LEFT) & KEY_JUST_PRESSED(BUTTON_LEFT, currentButtons, previousButtons)) {
          s1.color = RED;
          state = PLAY;
          fillScreenDMA(BLACK);
          drawImageDMA(140, 0, 56, 16, Score);
          drawChar(145, 38, '0', WHITE);
        }
        if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          main();
        }
        break;
      case PLAY:
        drawStar(20, 20);
        drawStar(40, 60);
        drawStar(70, 40);
        drawStar(90, 70);
        drawStar(110, 20);
        drawStar(130, 60);
        drawStar(160, 40);
        drawStar(180, 70);
        drawStar(200, 20);
        drawStar(220, 60);
        drawSprite(120, 120, s1.color);
        drawGoalTile(GREEN);
        state = STARTPLAYING;
        // state = ?
        break;
      case STARTPLAYING:
        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (s1.col != 0) {
            unDrawStar(s1.row, s1.col);
            drawSprite(s1.row, s1.col - 1, s1.color);
            s1.col -= 1;
            state = DRAWSTARS;
            break;
          }
        }
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (s1.row != 228) {
            unDrawStar(s1.row, s1.col);
            drawSprite(s1.row + 1, s1.col, s1.color);
            s1.row += 1;
            state = DRAWSTARS;
            break;
          }
        }
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (s1.row != 12) {
            unDrawStar(s1.row, s1.col);
            drawSprite(s1.row - 1, s1.col, s1.color);
            s1.row -= 1;
            state = DRAWSTARS;
            break;
          }
        }
        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (s1.col != 142) {
            unDrawStar(s1.row, s1.col);
            drawSprite(s1.row, s1.col + 1, s1.color);
            s1.col += 1;
            state = DRAWSTARS;
            break;
          }
        }
        if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          main();
        }
        if (KEY_DOWN_NOW(BUTTON_START) & KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          if ((star1.caught == 0) & (s1.row >= star1.row - 5) & (s1.row <= star1.row + 5) & (s1.col >= star1.col - 5) & (s1.col <= star1.col + 5)) {
            s1.score++;
            star1.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star2.caught == 0) & (s1.row >= star2.row - 5) & (s1.row <= star2.row + 5) & (s1.col >= star2.col - 5) & (s1.col <= star2.col + 5)) {
            s1.score++;
            star2.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star3.caught == 0) & (s1.row >= star3.row - 5) & (s1.row <= star3.row + 5) & (s1.col >= star3.col - 5) & (s1.col <= star3.col + 5)) {
            s1.score++;
            star3.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star4.caught == 0) & (s1.row >= star4.row - 5) & (s1.row <= star4.row + 5) & (s1.col >= star4.col - 5) & (s1.col <= star4.col + 5)) {
            s1.score++;
            star4.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star5.caught == 0) & (s1.row >= star5.row - 5) & (s1.row <= star5.row + 5) & (s1.col >= star5.col - 5) & (s1.col <= star5.col + 5)) {
            s1.score++;
            star5.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star6.caught == 0) & (s1.row >= star6.row - 5) & (s1.row <= star6.row + 5) & (s1.col >= star6.col - 5) & (s1.col <= star6.col + 5)) {
            s1.score++;
            star6.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star7.caught == 0) & (s1.row >= star7.row - 5) & (s1.row <= star7.row + 5) & (s1.col >= star7.col - 5) & (s1.col <= star7.col + 5)) {
            s1.score++;
            star7.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star8.caught == 0) & (s1.row >= star8.row - 5) & (s1.row <= star8.row + 5) & (s1.col >= star8.col - 5) & (s1.col <= star8.col + 5)) {
            s1.score++;
            star8.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star9.caught == 0) & (s1.row >= star9.row - 5) & (s1.row <= star9.row + 5) & (s1.col >= star9.col - 5) & (s1.col <= star9.col + 5)) {
            s1.score++;
            star9.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((star10.caught == 0) & (s1.row >= star10.row - 5) & (s1.row <= star10.row + 5) & (s1.col >= star10.col - 5) & (s1.col <= star10.col + 5)) {
            s1.score++;
            star10.caught = 1;
            fillScreenDMA(BLACK);
            state = DRAWSTARS;
            break;
          }
          if ((s1.row + 10 >= g1.row) & (s1.col + 10 >= g1.col)) {
            if (s1.score == 10) {
              state = WIN;
            } else {
              state = LOSE;
            }
          }
          break;
        }
        if ((s1.row + 10 >= g1.row) & (s1.col + 10 >= g1.col)) {
          if (s1.score == 10) {
            state = WIN;
          } else {
            state = LOSE;
          }
          break;
        }
        break;
      case DRAWSTARS:
        if (star1.caught == 0) {
          drawStar(20, 20);
        }
        if (star2.caught == 0) {
          drawStar(40, 60);
        }
        if (star3.caught == 0) {
          drawStar(70, 40);
        }
        if (star4.caught == 0) {
          drawStar(90, 70);
        }
        if (star5.caught == 0) {
          drawStar(110, 20);
        }
        if (star6.caught == 0) {
          drawStar(130, 60);
        }
        if (star7.caught == 0) {
          drawStar(160, 40);
        }
        if (star8.caught == 0) {
          drawStar(180, 70);
        }
        if (star9.caught == 0) {
          drawStar(200, 20);
        }
        if (star10.caught == 0) {
          drawStar(220, 60);
        }
        drawImageDMA(140, 0, 56, 16, Score);
        if (s1.score == 0) {
          drawChar(145, 38, '0', WHITE);
        } else if (s1.score == 1) {
          drawChar(145, 38, '1', WHITE);
        } else if (s1.score == 2) {
          drawChar(145, 38, '2', WHITE);
        } else if (s1.score == 3) {
          drawChar(145, 38, '3', WHITE);
        } else if (s1.score == 4) {
          drawChar(145, 38, '4', WHITE);
        } else if (s1.score == 5) {
          drawChar(145, 38, '5', WHITE);
        } else if (s1.score == 6) {
          drawChar(145, 38, '6', WHITE);
        } else if (s1.score == 7) {
          drawChar(145, 38, '7', WHITE);
        } else if (s1.score == 8) {
          drawChar(145, 38, '8', WHITE);
        } else if (s1.score == 9) {
          drawChar(145, 38, '9', WHITE);
        } else if (s1.score == 10) {
          drawChar(145, 38, '1', WHITE);
          drawChar(145, 44, '0', WHITE);
        }
        drawGoalTile(GREEN);
        drawSprite(s1.row, s1.col, s1.color);
        state = STARTPLAYING;
        break;
      case WIN:
        drawFullScreenImageDMA(TitleScreenTen);
        for (int i = 0; i < 912; i++) {
          if (i%20 == 0) {
            drawSprite(s2.row + (i), s2.col, s2.color);
          }
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            main();
            break;
          }
          if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            main();
          }
        }
        for (int i = 0; i < 912; i++) {
          if (i%20 == 0) {
            drawSprite(s2.row - (i), s2.col, s2.color);
          }
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            main();
            break;
          }
          if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            main();
          }
        }
        if (KEY_DOWN_NOW(BUTTON_START) & KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          main();
        }
        if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          main();
        }
        // state = ?
        break;
      case LOSE:
        if (s1.score == 0) {
          drawFullScreenImageDMA(TitleScreenZero);
        } else if (s1.score == 1) {
          drawFullScreenImageDMA(TitleScreenOne);
        } else if (s1.score == 2) {
          drawFullScreenImageDMA(TitleScreenTwo);
        } else if (s1.score == 3) {
          drawFullScreenImageDMA(TitleScreenThree);
        } else if (s1.score == 4) {
          drawFullScreenImageDMA(TitleScreenFour);
        } else if (s1.score == 5) {
          drawFullScreenImageDMA(TitleScreenFive);
        } else if (s1.score == 6) {
          drawFullScreenImageDMA(TitleScreenSix);
        } else if (s1.score == 7) {
          drawFullScreenImageDMA(TitleScreenSeven);
        } else if (s1.score == 8) {
          drawFullScreenImageDMA(TitleScreenEight);
        } else if (s1.score == 9) {
          drawFullScreenImageDMA(TitleScreenNine);
        }
        for (int i = 0; i < 912; i++) {
          if (i%20 == 0) {
            drawSprite(s2.row + (i), s2.col, s2.color);
          }
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            main();
            break;
          }
          if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            main();
          }
        }
        for (int i = 0; i < 912; i++) {
          if (i%20 == 0) {
            drawSprite(s2.row - (i), s2.col, s2.color);
          }
          if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
            main();
            break;
          }
          if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
            main();
          }
        }
        if (KEY_DOWN_NOW(BUTTON_START) & KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          main();
        }
        if (KEY_DOWN_NOW(BUTTON_SELECT) & KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          main();
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}